apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
type: Opaque
data:
  PRIVATE_VALUE: KioqKioqKioqKg==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config
data:
  CONFIG_VALUE: "Hello K8S"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sample
spec:
  revisionHistoryLimit: 0
  replicas: 2
  selector:
    matchLabels:
      app: sample
  strategy:
    rollingUpdate:
      maxSurge: 2       
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample-app
        image: sample-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8089
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: CONFIG_VALUE
          valueFrom:
            configMapKeyRef:
              name: sample-config
              key: CONFIG_VALUE
        - name: PRIVATE_VALUE
          valueFrom:
            configMapKeyRef:
              name: sample-secret
              key: PRIVATE_VALUE

---

apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  type: NodePort
  selector:
    app: sample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8089
    nodePort: 30082